BLOG/urls.py
from django.urls import path
from .views import (
            AboutView,CreateBlog,Bloglist

)


app_name = "blog"

urlpatterns = [
    path('create/', CreateBlog.as_view(), name='create'),
    path('', Bloglist.as_view(), name='blog'),
]

Mperson/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeDoneView,
    PasswordChangeView
)


from django.contrib.auth import views as auth_views

from users_app.views import SignupView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('core.urls', namespace="core")),
    path('userdash/',  include('UserDashboard.urls', namespace="userdashboard")),
    path('blog/',  include('BLOG.urls', namespace="blog")),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='SignupView'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # this area is for rest password
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # rest end here

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'), 
        name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), 
        name='password_change_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    HometView, AboutView, Privacy, Terms, Complaints,
    Contact, missing_person,AdminDashboard,Admin_Missing_People_Report_all,
    Admin_Missing_People_Report_active, Admin_Missing_People_Report_found, Admin_Missing_People_Report_Pending,
    All_user_list, Create_missing_person,AdminUpdate,Enquiries_message,
    EmergencyView, Howitwork, Found_people, Blogview, BlogDetail, Missing_people
)


app_name = "core"

urlpatterns = [
    path('', HometView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('Privacy/', Privacy.as_view(), name='privacy'),
    path('Howitwork/', Howitwork.as_view(), name='Howitwork'),
    path('Found_people/', Found_people.as_view(), name='Found_people'),
    path('Missing_people/', Missing_people.as_view(), name='Missing_people'),
    path('Blogview/', Blogview.as_view(), name='Blogview'),
    path('BlogDetail/', BlogDetail.as_view(), name='BlogDetail'),
   
    path('Terms/', Terms.as_view(), name='Terms'),
    path('Complaints/', Complaints.as_view(), name='Complaints'),
    path('Contact/', Contact.as_view(), name='Contact'),
    path('missing_person/', missing_person.as_view(), name='missing_person'),

    # this is for admin dashborad
    path('AdminDashboard/', AdminDashboard.as_view(), name='AdminDashboard'),
    path('Admin_Missing_People_Report_all/', Admin_Missing_People_Report_all.as_view(), name='Admin_Missing_People_Report_all'), 
    path('Admin_Missing_People_Report_active/', Admin_Missing_People_Report_active.as_view(), name='Admin_Missing_People_Report_active'), 
    path('Admin_Missing_People_Report_found/', Admin_Missing_People_Report_found.as_view(), name='Admin_Missing_People_Report_found'), 
    path('Admin_Missing_People_Report_Pending/', Admin_Missing_People_Report_Pending.as_view(), name='Admin_Missing_People_Report_Pending'), 

    path('All_user_list/', All_user_list.as_view(), name='All_user_list'), 
    path('Create_missing_person/', Create_missing_person.as_view(), name='Create_missing_person'), 
    # admin dashbord end here Create_missing_person


    
    path('AdminUpdate/', AdminUpdate.as_view(), name='AdminUpdate'),  

    
    path('Enquiries_message/', Enquiries_message.as_view(), name='Enquiries_message'), 
    
    path('Emergency/', EmergencyView.as_view(), name='Emergency'),  



    # for UserDashboard 

    # path('UserDashboard/', UserDashboard.as_view(), name='UserDashboard'),  
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <link rel="stylesheet"  href="{% static 'css/main.css' %}">


</head>
<body>
    {% include 'navbar.html' %}


    {% block content %}
    
    
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light navbar__">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'core:home' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    How it works
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{%url 'core:Contact' %} ">Contact Us</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{ url 'Blog:all_blogs' %}">Blog</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Store</a></li>
                </ul>
              </li>




          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Activites
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Missing Person</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{ url 'createmissing' %}">Report an Event</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Found People</a></li> 

              {% if user.is_authenticated %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'core:AdminDashboard' %}">dashboard</a> </li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{ url 'account_update' %}">Update Profile</a>  </li>  
              {% endif %}
            </ul>
          </li>
        </ul>


        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 newguy">





            <!-- <li class="nav-item">
                <a class="nav-link">welcome {{request.user}}</a>
            </li> -->





            
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a> 
            </li>

            {%else%}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>

            <li class="nav-item">
                <a class="nav-link btn" href="{% url 'SignupView' %}">Create Account</a>
                <!-- <button class="btn btn-outline-success">Search</button> -->
            </li>
            {% endif %}

          </ul>


      </div>
    </div>
  </nav>

templates/password_change.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>


{{request.user}}


<form id="id_password_change_form" method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
    <h1> old</h1>
    <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password" required="true">
    <h1> new one</h1>
    <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1" required="true">
    <h1> new to</h1> 
    <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2" required="true">

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" type="submit">Update</button>  
</form>


{% endblock %}

templates/password_change_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been Updated.</p>
	</div>
</div>

{% endblock %}